### ISSUE TITLE
Minor propositions for derive_flood_extents export  

### ISSUE THREAD

**Issue by ddebarros-mapaction** [cateseale/flood-mapper#1]
I think it would be nice to have some freedom on choosing the path and filenames for the export. Also, if possible, adding two other tiff files, one representing the region before and one after the flooding (with an average during the period), could be a good idea to make visual analysis of the flooding zone easier.

**Comment by cateseale** [comment]
Opened new issue #4 for the second part referring to adding new tiff exports.

Will keep this issue for user-specified export filenames.

**Comment by cateseale** [comment]
Published v 0.1.1 which adds `filename` parameter to `export_flood_data()` or optionally `export_filename` parameter to `derive_flood_extents()`
