### ISSUE TITLE
Not able to install using pip

### ISSUE THREAD

**Issue by ddebarros-mapaction** [cateseale/flood-mapper#2]
I was not able to install the package using pip install flood-mapper. Tried on google colab, jupyter notebook and ubuntu terminal and got the same message each time "ERROR: Could not find a version that satisfies the requirement flood-mapper (from versions: none) ERROR: No matching distribution found for flood-mapper". Always possible to import it locally after downloading the .py file though

**Comment by cateseale** [comment]
Could you try `pip3 install flood-mapper`? Working for me in Python 3.9, I think the project dependency is set to ^3.9, but maybe it doesn't have to be that high.

**Comment by pjgerrits** [comment]
Hi @cateseale, thanks,I tried `pip3 install flood-mapper` which worked for me with Python 3.9 without issues.

**Comment by cateseale** [comment]
Thanks Piet - closing this as it sounds like a Python 2 thing.
